# Generated by Django 6.0.3 on 2026-03-14 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('NID', 'National ID'), ('TIN', 'Tax ID (TIN)')], default='NID', max_length=3)),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('front_side', models.ImageField(upload_to='nids/front/')),
                ('back_side', models.ImageField(upload_to='nids/back/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending AI Check'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
