# Generated by Django 6.0.4 on 2026-04-21 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_serviceagreement_milestone_encryptedmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='amount_or_value',
        ),
        migrations.AddField(
            model_name='milestone',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Escrow Hold', 'Escrow Hold'), ('Earnings', 'Earnings'), ('Service Fee', 'Service Fee')], max_length=20)),
                ('payment_method', models.CharField(choices=[('bKash', 'bKash'), ('SSLCommerz', 'SSLCommerz'), ('Internal Wallet', 'Internal Wallet')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
