# Generated by Django 6.0.4 on 2026-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_avatar_customuser_bio_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobproposal',
            name='acceptance_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobproposal',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
