# Generated by Django 6.0.4 on 2026-04-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_avatar_customuser_bio_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_uid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
